add error if mysql set on remote host but not found

diff --git a/abiquo-server/abiquo-liquibase b/abiquo-server/abiquo-liquibase
--- a/abiquo-server/abiquo-liquibase
+++ b/abiquo-server/abiquo-liquibase
@@ -41,10 +41,18 @@ exit 1
 fi
 
 if [ "$DBHOST" == "localhost" ]; then
-  NPROC=$(netstat -tupan | grep $DBPORT | wc -l)
+  NPROC=$(netstat -tan | grep $DBPORT | wc -l)
   if [ $NPROC -eq 0 ]; then
-    echo "Cannot find MySQL running on localhost"
-    echo "Please set the right parameters to connect to the MySQL database."
+    echo "Cannot find MySQL service running on localhost"
+    echo "Please set the right parameters to connect to the MySQL server."
+    exit 1
+  fi
+else
+  mysql -u$DBUSER --password="$DBPASSWORD" -h"$DBHOST" -P"$DBPORT"  -e ""
+  RETURN=$?
+  if [ $RETURN -gt 0 ]; then
+    echo "Cannot connect to mysql server"
+    echo "Please set the right parameters to connect to the MySQL server."
     exit 1
   fi
 fi
