add error if mysql set on remote host but not found

diff --git a/abiquo-server/abiquo-liquibase b/abiquo-server/abiquo-liquibase
--- a/abiquo-server/abiquo-liquibase
+++ b/abiquo-server/abiquo-liquibase
@@ -40,6 +40,22 @@ echo "Cannot find the abiquo properties file."
 exit 1
 fi
 
+if [ "$DBHOST" == "localhost" ]; then
+  NPROC=$(netstat -tan | grep $DBPORT | wc -l)
+  if [ $NPROC -eq 0 ]; then
+    echo "Cannot find MySQL service running on localhost"
+    echo "Please set the right parameters to connect to the MySQL server."
+    exit 1
+  fi
+else
+  mysql -u$DBUSER --password="$DBPASSWORD" -h"$DBHOST" -P"$DBPORT"  -e ""
+  RETURN=$?
+  if [ $RETURN -gt 0 ]; then
+    echo "Cannot connect to mysql server"
+    echo "Please set the right parameters to connect to the MySQL server."
+    exit 1
+  fi
+fi
 pushd $DATADIR > /dev/null
 
 echo "Upgrading accounting schema"
